version: '3.8'

services:
    redis:
        image: redis:alpine
        container_name: animate_redis
        ports:
            - "6379:6379"

    backend:
        build: ./backend
        container_name: animate_backend
        restart: always
        command: >
          sh -c "python3 manage.py migrate 
          && ./Run.sh
          && uwsgi --ini uwsgi.ini"
        volumes:
          - ./backend/static:/usr/src/app/static
        ports:
          - "8080:8080"
          - "8081:8081"
        environment:
          - PYTHONUNBUFFERED=TURE
          - REDIS=redis
        depends_on:
        - redis

    nginx:
        build: .
        container_name: animate_nginx
        restart: always
        ports:
          - "44200:44200"
        depends_on:
          - backend
        volumes:
          - ./backend/static:/usr/src/app/static

