# Generated by Django 3.2.7 on 2021-12-04 18:48

import Database.models.my
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimateEpisodeInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('done', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=Database.models.my.upload_video_path)),
            ],
            options={
                'db_table': 'AnimateEpisodeInfo',
            },
        ),
        migrations.CreateModel(
            name='AnimateInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('animate_type', models.CharField(max_length=32)),
                ('premiere_date', models.CharField(max_length=16)),
                ('episode', models.CharField(max_length=16)),
                ('author', models.CharField(max_length=32)),
                ('official_website', models.URLField()),
                ('remarks', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to=Database.models.my.upload_image_path)),
                ('synopsis', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'db_table': 'AnimateInfo',
            },
        ),
        migrations.CreateModel(
            name='FinishAnimateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(unique=True)),
                ('image', models.ImageField(upload_to=Database.models.my.upload_image_path)),
                ('info', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'MyselfFinishAnimate',
            },
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animate_website_name', models.CharField(max_length=32)),
                ('animate_name', models.CharField(max_length=128)),
                ('episode_name', models.CharField(max_length=64)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='LoveGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('action', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'System',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_model', to='Database.animateepisodeinfomodel')),
            ],
            options={
                'db_table': 'MyselfDownload',
            },
        ),
        migrations.CreateModel(
            name='AnimateEpisodeTsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=32)),
                ('done', models.BooleanField(default=False)),
                ('ts', models.FileField(upload_to=Database.models.my.upload_ts_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_model', to='Database.animateepisodeinfomodel')),
            ],
            options={
                'db_table': 'AnimateEpisodeTs',
            },
        ),
        migrations.AddField(
            model_name='animateepisodeinfomodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_info_model', to='Database.animateinfomodel'),
        ),
    ]
