# Generated by Django 3.2.10 on 2022-01-08 19:33

import Database.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime1AnimateEpisodeInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('done', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=Database.models.base.upload_video_path)),
                ('published_updated_date', models.DateField()),
                ('updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Anime1AnimateEpisodeInfo',
                'ordering': ('published_updated_date',),
            },
        ),
        migrations.CreateModel(
            name='Anime1AnimateInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(unique=True)),
                ('episode', models.CharField(max_length=16)),
                ('years', models.CharField(max_length=8)),
                ('season', models.CharField(max_length=32)),
                ('subtitle_group', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'Anime1AnimateInfo',
            },
        ),
        migrations.CreateModel(
            name='MyHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animate_website_name', models.CharField(max_length=32)),
                ('animate_name', models.CharField(max_length=128)),
                ('episode_name', models.CharField(max_length=64)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MyHistory',
                'ordering': ('-download_date',),
            },
        ),
        migrations.CreateModel(
            name='MyLoveGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'MyLoveGroup',
            },
        ),
        migrations.CreateModel(
            name='MyselfAnimateEpisodeInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('done', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=Database.models.base.upload_video_path)),
            ],
            options={
                'db_table': 'MyselfAnimateEpisodeInfo',
            },
        ),
        migrations.CreateModel(
            name='MyselfAnimateInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('animate_type', models.CharField(max_length=32)),
                ('premiere_date', models.CharField(max_length=16)),
                ('episode', models.CharField(max_length=16)),
                ('author', models.CharField(max_length=32)),
                ('official_website', models.URLField()),
                ('remarks', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to=Database.models.base.upload_image_path)),
                ('synopsis', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'db_table': 'MyselfAnimateInfo',
            },
        ),
        migrations.CreateModel(
            name='MyselfFinishAnimateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(unique=True)),
                ('image', models.ImageField(upload_to=Database.models.base.upload_image_path)),
                ('info', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'MyselfFinishAnimate',
            },
        ),
        migrations.CreateModel(
            name='MySettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myself_download_value', models.IntegerField(default=1)),
                ('anime1_download_value', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'MySettings',
            },
        ),
        migrations.CreateModel(
            name='MySystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('action', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MySystem',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='MyselfDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_model', to='Database.myselfanimateepisodeinfomodel')),
            ],
            options={
                'db_table': 'MyselfDownload',
            },
        ),
        migrations.CreateModel(
            name='MyselfAnimateEpisodeTsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=32)),
                ('done', models.BooleanField(default=False)),
                ('ts', models.FileField(upload_to=Database.models.base.upload_ts_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_model', to='Database.myselfanimateepisodeinfomodel')),
            ],
            options={
                'db_table': 'MyselfAnimateEpisodeTs',
            },
        ),
        migrations.AddField(
            model_name='myselfanimateepisodeinfomodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_info_model', to='Database.myselfanimateinfomodel'),
        ),
        migrations.CreateModel(
            name='Anime1DownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_model', to='Database.anime1animateepisodeinfomodel')),
            ],
            options={
                'db_table': 'Anime1Download',
            },
        ),
        migrations.AddField(
            model_name='anime1animateepisodeinfomodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_info_model', to='Database.anime1animateinfomodel'),
        ),
    ]
