# Generated by Django 3.2.10 on 2022-01-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettingsmodel',
            name='myself_search_animate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
