# Generated by Django 3.2.7 on 2021-10-12 21:46

import Database.models.my
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateepisodeinfomodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Database.models.my.upload_video_path),
        ),
        migrations.AlterField(
            model_name='animateepisodeinfomodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_info_model', to='Database.animateinfomodel'),
        ),
    ]
