# Generated by Django 3.2.7 on 2021-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateepisodeinfomodel',
            name='download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animateepisodeinfomodel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
