# Generated by Django 3.2.7 on 2021-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateepisodeinfomodel',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
