# Generated by Django 3.2.7 on 2021-11-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_animateepisodeinfomodel_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animateepisodeinfomodel',
            name='hide',
        ),
    ]
