# Generated by Django 3.2.10 on 2022-01-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_mysettingsmodel_myself_search_animate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysettingsmodel',
            old_name='myself_search_animate',
            new_name='myself_finish_animate_date',
        ),
    ]
