# Generated by Django 3.2.10 on 2022-01-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_rename_myself_search_animate_mysettingsmodel_myself_finish_animate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettingsmodel',
            name='myself_finish_animate_update',
            field=models.BooleanField(default=False),
        ),
    ]
