# Generated by Django 3.2.7 on 2021-11-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_remove_animateepisodeinfomodel_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_model', to='Database.animateepisodeinfomodel')),
            ],
        ),
    ]
