# Generated by Django 3.2.7 on 2021-11-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_downloadmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadmodel',
            table='MyselfDownload',
        ),
    ]
