# Generated by Django 3.2.7 on 2021-12-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_alter_historymodel_download_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogModel',
            new_name='SystemModel',
        ),
        migrations.AlterModelOptions(
            name='systemmodel',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterModelTable(
            name='systemmodel',
            table='System',
        ),
    ]
