export const weekAnimateState = 'weekAnimateState'
export const animateInfoState = 'animateInfoState'
export const loadingState = 'loadingState'
export const finishListState = 'finishListState'
export const finishAnimateState = 'finishAnimateState'
export const finishAnimateUpdateState = 'finishAnimateUpdateState'
export const finishAnimateUpdateButtonState = 'finishAnimateUpdateButtonState'
export const checkboxAnimateEpisodeState = 'checkboxAnimateEpisodeState'
export const downloadMyselfAnimateState = 'downloadMyselfAnimateState'
export const animateCollectState = 'animateCollectState'

export const weekAnimateAction = 'weekAnimateAction'
export const animateInfoAction = 'animateInfoAction'
export const finishListAction = 'finishListAction'
export const finishAnimateAction = 'finishAnimateAction'
export const animateCollectAction = 'animateCollectAction'

export const addWeekAnimateMutation = 'addWeekAnimateMutation'
export const addAnimateInfoMutation = 'addAnimateInfoMutation'
export const loadingMutation = 'loadingMutation'
export const addFinishListMutation = 'addFinishListMutation'
export const addFinishAnimateMutation = 'addFinishAnimateMutation'
export const finishAnimateUpdateButtonMutation = 'finishAnimateUpdateButtonMutation'
export const addCheckboxAnimateEpisodeMutation = 'addCheckboxAnimateEpisodeMutation'
export const removeCheckboxAnimateEpisodeMutation = 'removeCheckboxAnimateEpisodeMutation'
export const downloadMyselfAnimateMutation = 'downloadMyselfAnimateMutation'
export const searchMyselfAnimateMutation = 'searchMyselfAnimateMutation'
export const animateCollectMutation = 'animateCollectMutation'

export const downloadMyselfAnimateGetters = 'downloadMyselfAnimateGetters'
export const finishAnimateGetters = 'finishAnimateGetters'
