export const weekAnimateState = 'weekAnimateState'
export const animateInfoState = 'animateInfoState'
export const loadingState = 'loadingState'
export const finishListState = 'finishListState'
export const finishAnimateState = 'finishAnimateState'
export const finishAnimateUpdateState = 'finishAnimateUpdateState'
export const finishAnimateUpdateButtonState = 'finishAnimateUpdateButtonState'
export const downloadMyselfAnimateState = 'downloadMyselfAnimateState'

export const weekAnimateAction = 'weekAnimateAction'
export const animateInfoAction = 'animateInfoAction'
export const finishListAction = 'finishListAction'
export const finishAnimateAction = 'finishAnimateAction'
export const animateInfoEpisodeInfoAction = 'animateInfoEpisodeInfoAction'
export const searchAnimateAction = 'searchAnimateAction'

export const addWeekAnimateMutation = 'addWeekAnimateMutation'
export const addAnimateInfoMutation = 'addAnimateInfoMutation'
export const loadingMutation = 'loadingMutation'
export const addFinishListMutation = 'addFinishListMutation'
export const finishAnimateMutation = 'finishAnimateMutation'
export const finishAnimateInitMutation = 'finishAnimateInitMutation'
export const finishAnimateUpdateButtonMutation = 'finishAnimateUpdateButtonMutation'
export const downloadMyselfAnimateMutation = 'downloadMyselfAnimateMutation'
export const searchMyselfAnimateMutation = 'searchMyselfAnimateMutation'
export const animateInfoEpisodeInfoMutation = 'animateInfoEpisodeInfoMutation'
export const searchAnimateMutation = 'searchAnimateMutation'

export const downloadMyselfAnimateGetters = 'downloadMyselfAnimateGetters'
export const finishAnimateGetters = 'finishAnimateGetters'
