export const weekAnimateState = 'weekAnimateState'
export const activeWeekState = 'activeWeekState'
export const animateInfoState = 'animateInfoState'
export const loadingState = 'loadingState'
export const finishListState = 'finishListState'
export const finishAnimateState = 'finishAnimateState'
export const displayFinishAnimateState = 'displayFinishAnimateState'
export const finishAnimateUpdateState = 'finishAnimateUpdateState'
export const finishAnimateUpdateButtonState = 'finishAnimateUpdateButtonState'
export const checkboxAnimateEpisodeState = 'checkboxAnimateEpisodeState'
export const downloadMyselfAnimateState = 'downloadMyselfAnimateState'

export const weekAnimateAction = 'weekAnimateAction'
export const animateInfoAction = 'animateInfoAction'
export const finishListAction = 'finishListAction'
export const finishAnimateAction = 'finishAnimateAction'

export const addWeekAnimateMutation = 'addWeekAnimateMutation'
export const changeActiveWeekMutation = 'changeActiveWeekMutation'
export const addAnimateInfoMutation = 'addAnimateInfoMutation'
export const loadingMutation = 'loadingMutation'
export const addFinishListMutation = 'addFinishListMutation'
export const addFinishAnimateMutation = 'addFinishAnimateMutation'
export const finishAnimateUpdateButtonMutation = 'finishAnimateUpdateButtonMutation'
export const addCheckboxAnimateEpisodeMutation = 'addCheckboxAnimateEpisodeMutation'
export const removeCheckboxAnimateEpisodeMutation = 'removeCheckboxAnimateEpisodeMutation'
export const downloadMyselfAnimateMutation = 'downloadMyselfAnimateMutation'
export const searchMyselfAnimateMutation = 'searchMyselfAnimateMutation'
export const displayFinishAnimateMutation = 'displayFinishAnimateMutation'

export const downloadMyselfAnimateGetters = 'downloadMyselfAnimateGetters'
